Theming and minor housekeeping
GetStream/stream-feed-flutter pull request #132
Opened 2021-08-27 15:27 UTC by GroovinChip

This PR contains basic work for theming capabilities in `stream_feed_flutter`. It also contains some minor housekeeping work for the same package.

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

## Description of the pull request

2021-08-31 15:12 UTC, sachaarbonel requested changes
Left a reviews based on our discussion but other than that looks good to me

2021-08-31 15:12 UTC, sachaarbonel commented on packages/stream_feed_flutter/lib/src/utils/extensions.dart
>    TextStyle style() => <Tag, TextStyle>{
no longer useful I think

2021-08-31 15:12 UTC, sachaarbonel commented on packages/stream_feed_flutter/lib/src/widgets/comment/item.dart
> +      const TextStyle(
Same here add a way to customize username display

2021-08-31 15:12 UTC, sachaarbonel commented on packages/stream_feed_flutter/lib/src/widgets/dialogs/gif.dart
> +        border: Border.all(color: Colors.blue),
would be nice to have border-radius and color in the future too. One property for all the dialogs is enough I think

2021-08-31 15:12 UTC, sachaarbonel commented on packages/stream_feed_flutter/lib/src/widgets/og/card.dart
> +                        style: const TextStyle(
would be nice to have a way to customize the textStyle of the card too. Something like `cardTitleTextStyle`

2021-08-31 15:12 UTC, sachaarbonel commented on packages/stream_feed_flutter/lib/src/widgets/og/card.dart
>                          og.description!, //TODO: handle null
Same here. Something like `cardDescTextStyle`

2021-08-31 15:12 UTC, sachaarbonel commented on packages/stream_feed_flutter/lib/src/widgets/user/user_bar.dart
> +      const TextStyle(
add a way to customize avatar text style in the theme

2021-08-31 15:15 UTC, GroovinChip commented on packages/stream_feed_flutter/lib/src/utils/extensions.dart
>    TextStyle style() => <Tag, TextStyle>{
What in particular is no longer useful?

2021-08-31 15:20 UTC, GroovinChip commented on packages/stream_feed_flutter/lib/src/widgets/comment/item.dart
> +      const TextStyle(
I'm not sure of how to do this without adding a whole class just for it, do you have any ideas?

2021-08-31 15:21 UTC, GroovinChip commented on packages/stream_feed_flutter/lib/src/widgets/dialogs/gif.dart
> +        border: Border.all(color: Colors.blue),
Can do this with a `GifDialogTheme` and `GifDialogThemeData`

2021-08-31 15:26 UTC, sachaarbonel commented on packages/stream_feed_flutter/lib/src/utils/extensions.dart
>    TextStyle style() => <Tag, TextStyle>{
The extension method style is now handled in InteractiveText via ReactionTheme.of(context).hashtagTextStyle etc. And the method spans is never used I think

2021-08-31 15:28 UTC, sachaarbonel commented on packages/stream_feed_flutter/lib/src/widgets/dialogs/gif.dart
> +        border: Border.all(color: Colors.blue),
sounds good

2021-08-31 15:29 UTC, GroovinChip commented on packages/stream_feed_flutter/lib/src/utils/extensions.dart
>    TextStyle style() => <Tag, TextStyle>{
So the whole extension method needs to go?

2021-08-31 15:37 UTC, GroovinChip commented on packages/stream_feed_flutter/lib/src/widgets/dialogs/gif.dart
> +        border: Border.all(color: Colors.blue),
Done

2021-08-31 16:43 UTC, GroovinChip commented on packages/stream_feed_flutter/lib/src/widgets/user/user_bar.dart
> +      const TextStyle(
Similar problem here as for item.dart

2021-08-31 21:01 UTC, sachaarbonel approved these changes
LGTM

2021-09-01 17:51 UTC, sachaarbonel approved these changes
LGTM

2021-09-01 17:51 UTC, merged