Like button
GetStream/stream-feed-flutter pull request #84
Opened 2021-05-31 18:20 UTC by sachaarbonel

2021-05-31 23:22 UTC, Nash0x7E2 requested changes

2021-05-31 23:22 UTC, Nash0x7E2 commented on packages/stream_feed_flutter/lib/src/like_button.dart
> +  LikeButton({this.reaction, this.activity});
Constructors should be sorted first and include documentation for the current widgets and their params.

2021-05-31 23:22 UTC, Nash0x7E2 commented on packages/stream_feed_flutter/lib/src/like_button.dart
> +          reaction?.ownChildren?['like'] ?? activity?.ownReactions?['like'],
You may want to add some asserts for `reaction` and `activity`. If both params are null, then this code will fail.

2021-06-24 16:28 UTC, xsahil03x commented on packages/stream_feed_flutter_core/lib/src/extensions.dart
> +      where((reaction) => reaction.kind == kind).toList();
```suggestion
  List<Reaction> filterByKind(String kind) =>
      where((reaction) => reaction.kind == kind).toList();
```

2021-06-24 16:33 UTC, merged